{
  branches: [
    {name: 'master'},
  ],
  "plugins": [
    ["@semantic-release/commit-analyzer", {
      "preset": "angular",
      "releaseRules": [
        {"breaking": true, "release": "minor"},
        {"type": "feat", "release": "patch"},
        {"type": "refactor", "release": "patch"},
        {"type": "style", "release": false},
        {"type": "docs", "release": false},
        {"type": "test", "release": false},
        {"type": "chore", "release": false},
        {"type": "build", "release": false},
        {"type": "ci", "release": false},
        {"scope": "no-release", "release": false}
      ]
    }],
    ["@semantic-release/release-notes-generator", {
      "preset": "conventionalcommits",
      "presetConfig": {
        "types": [
          {"type": "feat", "section": "Features"},
          {"type": "fix", "section": "Bug Fixes"},
          {"type": "perf", "section": "Performance Improvements"},
          {"type": "revert", "section": "Reverts"},
          {"type": "docs", "section": "Documentation"},
          {"type": "refactor", "section": "Code Refactoring", "hidden": true},
          {"type": "chore", "section": "Chores", "hidden": true},
          {"type": "test", "section": "Tests"},
          {"type": "build", "section": "Build", "hidden": true},
          {"type": "ci", "section": "Continuous Integration", "hidden": true}
        ]
      }
    }],
    ["@google/semantic-release-replace-plugin", {
      "replacements": [
        {
          "files": ["src/gecore/__init__.py"],
          "from": "__VERSION__ = \".*\"",
          "to": "__VERSION__ = \"${nextRelease.version}\"",
          "results": [
            {
              "file": "src/gecore/__init__.py",
              "hasChanged": true,
              "numMatches": 1,
              "numReplacements": 1
            }
          ],
          "countMatches": true
        }
      ]
    }],
    ["@semantic-release/exec", {
      "prepareCmd": "tox -e py39",
      "publishCmd": "tox -e py39-deploy",
    }],
    ["@semantic-release/github", {
      "assets": [{"path": ".tox/dist/*.tar.gz", "label": "Ge-Core"}],
      "failTitle": false
    }
    ],
  ]
}