[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.tox]
legacy_tox_ini = """
[tox]
isolated_build = True
envlist = py39

[testenv]
deps = pytest >= 6.2.4
       -rrequirements.txt
commands = pytest
"""