[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.tox]
legacy_tox_ini = """
[tox]
isolated_build = True
envlist = py39

[gh-actions]
python =
    3.9: py39

[testenv]
changedir = tests
deps = -rrequirements/test.txt
commands = pytest
"""